### ISSUE TITLE
XML files created, but generated HTML report doesn't contain any data

### ISSUE THREAD

**Issue by tourdedave** [allure-framework/allure-rspec#1]
I'm using version 1.3.9 of the allure-cli tool to generate the report.

According to [the FAQ & Troubleshooting on allure-core](https://github.com/allure-framework/allure-core/wiki/FAQ-and-Troubleshooting#xml-files-are-successfully-created-during-test-run-but-no-html-report-is-then-generated) the XML schema used may be mismatched. But I'm unsure how to verify that, or how try a different version of allure-cli since I'm on OSX and it looks like [1.3.9 is the only version available](https://github.com/allure-framework/allure-core/wiki/Allure-Command-Line-Interface#mac).

**Comment by nachiketk21** [comment]
I am facing issues with the same code as above the details are here [http://stackoverflow.com/questions/43978493/allure-rspec-unable-to-see-any-data-in-html-report](url)
