### ISSUE TITLE
Enhancement Request: before(:step) after(:step)

### ISSUE THREAD

**Issue by maticon** [allure-framework/allure-rspec#14]
To properly get the reporting right, I'm using the step keyword inside the it blocks.  Part of our automated requirements is to update the test step status in our test case management tool (Zephyr).  Would it be possible to add before(:step) and after(:step) hooks or is that outside the scope of this tool?  Without it, I'll have to move back to using it blocks for each step.

``` Ruby
after(:step) do |x|
    update_zephyr_step_result(x)
end

it 'SC-12345' do
    # Pre-Requisites
    scanners_page = @dashboard_page.to_scanners

    # Steps
    step @zephyr_steps[:steps][1][:step] do 
        @scanners_add_page = scanners_page.click_add_button() 
    end
end
```

**Comment by Rodion13** [comment]
@smecsia Allure is super awesome. I have been using it actively! 
Do you know why by any chance first case isn't working? 
I was just about to implement it in my framework, but I am keep getting:

_You must explicitly give a scope (example, context, suite) or scope alias (each, all) when using symbols as metadata for a hook. (ArgumentError)_

**Comment by smecsia** [comment]
@Rodion13 Thank you for your response. Could you provide a sample code which reproduces your problem? That would be very helpful.

**Comment by Rodion13** [comment]
@smecsia This can be reproduces when after(:step) or before(:step) are in spec_helper.rb 
```ruby
RSpec.configure do |config|
   config.after(:step) do |e|
      puts "After step do smth"
    end
  end
```

__You must explicitly give a scope (example, context, suite) or scope alias (each, all) when using symbols as metadata for a hook. (ArgumentError)__

**Comment by smecsia** [comment]
@Rodion13 Huh. There's a bug for now. You cannot use step hooks from the configuration. That's because of RSpec internals that are hard to extend (current implementation of this hook is a bit hacky). 
Nonetheless you can use step hooks within `describe` block.

**Comment by Nakilon** [comment]
I don't the whole idea of this.
