### ISSUE TITLE
Error when trying to re-run the tests

### ISSUE THREAD

**Issue by mpahuja** [allure-framework/allure-rspec#35]
This seems to be happening intermittently but in my Rake File I am re-running the failed tests and i see this error message which results in marking a false failure of my jenkins build
```
C:/Ruby193/lib/ruby/gems/1.9.1/gems/allure-ruby-adaptor-api-0.6.2/lib/allure-ruby-adaptor-api/builder.rb:118:in `build!': undefined method `each' for nil:NilClass (NoMethodError)
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/allure-rspec-0.5.3/lib/allure-rspec/formatter.rb:63:in `stop'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/reporter.rb:127:in `block in notify'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/reporter.rb:126:in `each'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/reporter.rb:126:in `notify'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/reporter.rb:122:in `stop'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/reporter.rb:106:in `finish'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/reporter.rb:60:in `report'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:25:in `run'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:80:in `run'
	from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:17:in `block in autorun'
```
Please note I am use allure-rspec (0.5.3) with Rspec 2.14.1
Snippet from Gemfile.lock
```
    allure-rspec (0.5.3)
      allure-ruby-adaptor-api (= 0.6.2)
      rspec (~> 2.14.0)
    allure-ruby-adaptor-api (0.6.2)
```
Can someone please guide me if I am missing something here?

**Comment by mpahuja** [comment]
@vania-pooh @smecsia Here is a repo that I created to be able to consistently reproduce the issue:
https://github.com/mpahuja/allure-rerun-fails There are instructions on the repo on how to use it!

Just so you are aware, I am running tests in parallel and then re-running the failed tests again in parallel.

So the issue happens when we run tests in parallel the second time and there are no suite file on one of the threads. 
So line number 118 on this file is where the error stack up to: https://github.com/allure-framework/allure-ruby-adaptor-api/blob/master/lib/allure-ruby-adaptor-api/builder.rb
which tells me that if we can add a condition to check self.suites.nil? before doing self.suites.each then that should fix this issue. And there is anyways a code to take care of suites.empty? condition.

**Comment by vania-pooh** [comment]
@mpahuja thank you for this example. Hope @smecsia will be able to review this soon because we have a big holidays set right now.

**Comment by smecsia** [comment]
@mpahuja Sorry for delay, we have very long NY holidays in Russia :). I'm looking into your PR...

**Comment by smecsia** [comment]
@mpahuja I wasn't able to run your example. I'm getting the following errors:
```
LoadError: cannot load such file -- /home/smecsia/projects/allure-rerun-fails/spec/helpers/failures_formatter
```
```
`require': cannot load such file -- ./spec/helpers/re_run_data_collector.rb (LoadError)
```
Make sure you've included all the required files.

**Comment by mpahuja** [comment]
Sorry I somehow missed one folder, please pull latest! @smecsia

**Comment by mpahuja** [comment]
@smecsia I am still testing all the changes but seems to be working now but now I see a deprecation warning now: 
The `:example_group` key in an example group's metadata hash is deprecated. Use the example group's hash directly for the computed keys and `:parent_example_group` to access the parent example group metadata instead. Called from C:/Ruby193/lib/ruby/gems/1.9.1/gems/allure-rspec-0.6.8/lib/allure-rspec/formatter.rb:95:in `yield'.

Not a big deal to have this but would be good if we can fix this as well. This was introduced as part of the other PR for the enhancement.

**Comment by mpahuja** [comment]
This issue seems to be resolved now. We can close this issue, will create an enhancement for getting rid of deprecation warning!
