### ISSUE TITLE
Deprecation warning when using the gem

### ISSUE THREAD

**Issue by mpahuja** [allure-framework/allure-rspec#43]
Here is the warning that is being currently shown:

The :example_group key in an example group's metadata hash is deprecated. Use the example group's hash directly for the computed keys and :parent_example_group to access the parent example group metadata instead. Called from C:/Ruby193/lib/ruby/gems/1.9.1/gems/allure-rspec-0.6.8/lib/allure-rspec/formatter.rb:95:in `yield'.

**Comment by smecsia** [comment]
Fixed in 0.6.9 release.
