### ISSUE TITLE
The screenshot are not getting added to the xml file

### ISSUE THREAD

**Issue by haridak** [allure-framework/allure-rspec#48]
I am using  Selenium WebDriver, RSpec with Allure. I see all the data in the test report, the screenshot is getting saved to the specified location but is not getting attached to the xml.
Any inputs on what could be the issue?
Version of Allure-Rspec: 0.6.8

**Comment by smecsia** [comment]
@haridak can you find your attachment inside the xml files? If it is there, then please indicate the version of allure generator, you're using.

**Comment by haridak** [comment]
<test-cases>
    <test-case start="1428005277416" stop="1428005307488" status="passed">
      <name>creating an object</name>
      <title>creating an object</title>
      <steps/>
      <attachments/>
      <labels>
        <label name="feature" value="objects"/>
      </labels>
      <parameters/>
    </test-case>
  </test-cases>

@smecsia Copied an except from xml file. I see attachment tag but no id/name/ of the attachment. Let me now if this does not answer your questions. Also, could you ellaborate on what is an allure generator?

**Comment by smecsia** [comment]
@haridak In general Allure generator - is one of the [available options](https://github.com/allure-framework/allure-core/wiki#generating-a-report). 
It seems there's no attached files in the resulting xml. Can you show me how you're attaching the screenshot in your tests?

**Comment by haridak** [comment]
Here is the piece of code -   

c.after(:each) do |test1|
    unless test1.exception.nil?
      attach_file("screenshot",
                  @driver.save_screenshot(File.join(Dir.pwd, "results/#{UUID.new.generate}.png")))
    end
    @driver.quit
  end

**Comment by smecsia** [comment]
@haridak Please note, that `attach_file` method accepts a reference to `File` object, while `save_screenshot`  returns a `string`.

**Comment by haridak** [comment]
and you are awesome! thanks :+1:
