### ISSUE TITLE
story: 'Story Name' metadata alongside feature: 'feature' shows duplicate tests

### ISSUE THREAD

**Issue by sharmarahul** [allure-framework/allure-rspec#51]
describe 'Example', feature: 'Some feature', story: 'some_story' do
      it 'first test case' do
         #pass
      end

      it 'second test case' do
         #pass
      end

reports 4 tests in the report. If I tag each example separately then that's not the case. Is it possible to not just have example inherit the story from parent?

**Comment by smecsia** [comment]
What do you mean by "reports 4 tests in the report"? 
As for the metadata, it is not possible, because it is meant to be inherited from parent. This is how [RSpec metadata](https://www.relishapp.com/rspec/rspec-core/docs/metadata/user-defined-metadata) works. Why do you want to avoid this?

**Comment by sharmarahul** [comment]
By 4 tests in report I mean if you configure Allure report to run on the test above it shows as 4 test cases rather than 2.

**Comment by smecsia** [comment]
I cannot reproduce this. Are you sure you're generating the report with empty results directory? Also please check the property `clean_dir` in allure-rspec configuration. It should be `true`.
```ruby
   AllureRSpec.configure do |c|
      c.clean_dir = true
    end
```

**Comment by d-konovalov** [comment]
Hi @smecsia I've got the same issue 
look at the screenshot 
http://screencast.com/t/Cxp7uGe3WH

22 - is the right number but I can see here the doubled one

**Comment by smecsia** [comment]
@d-konovalov This seems to be a problem of the newer Allure report builder versions (where labels inheritance works differently). We need to discuss this once again with @baev.

**Comment by smecsia** [comment]
This issue is related to [allure-core#714](https://github.com/allure-framework/allure-core/issues/714)

**Comment by smecsia** [comment]
@d-konovalov @sharmarahul We've just released version 1.4.22 of Allure. Please verify the problem with duplicated test cases is fixed.

**Comment by sharmarahul** [comment]
@smecsia Thanks. Will take a look.

**Comment by d-konovalov** [comment]
Hi @smecsia,
but what should I update to work with new version?
you've released allure-core but I don't have it even in Gemfile.lock as a dependency
and also I couldn't find any new versions for the allure jenkins plugin

So what should I do verify the problem with duplicated test cases?

**Comment by smecsia** [comment]
@d-konovalov The problem is not related with the allure-rspec itself. How do you build your report? You should try the newer version of one of the [report building tools](https://github.com/allure-framework/allure-core/wiki#generating-a-report).

**Comment by d-konovalov** [comment]
@smecsia 
I build it with help of allure jenkins plugin

**Comment by smecsia** [comment]
@d-konovalov You can specify the version of report builder in jenkins plugin configuration.

**Comment by dw512** [comment]
hi,I came up the same problems. When you add :feature to describe block,then the allure report reports the duplicate case numbers, but when you remove :feature from describe block, all will be ok.
I use allure-spec with the version 0.7.5, today i change it to 0.7.7,but it is the same problem,so i want to know when will this bug can be fixed? 
I find that this bug had been reported long times ago,but till today,it is still not be fixed,so i wish this bug can be fixed as soon as possible. thanks.

** the following is my configure code:**
AllureRSpec.configure do |config|
  config.output_dir = 'allure-results'
  config.clean_dir = true
  config.logging_level = Logger::DEBUG
end

**my case : **
describe "home page",:feature=>"home page" do
  before(:each) do
    navigate_to_home_page
    maximize_browser
  end
  it "home page item",:story=>"home page item",:severity=>:minor do
    expect(page).to have_selector(:xpath,XPATH['home_page']['logo'])
end
**my allure-spec report: **
![qq20160318-0 2x](https://cloud.githubusercontent.com/assets/12636008/13868036/04c52532-ed00-11e5-8e87-9680b6445596.png)

**Comment by smecsia** [comment]
@dw512 Have you read the discussion? The problem is not with the allure-rspec gem itself. You need to upgrade your [report build tool](https://github.com/allure-framework/allure-core/wiki#generating-a-report) to version 1.4.22.

**Comment by d-konovalov** [comment]
Hi @smecsia 
I'm still experiencing the issue even with 1.4.22 version chosen

![image](http://content.screencast.com/users/dmitrykonovalov/folders/Jing/media/54bfa90d-62c2-43e2-8d6f-8da0e891be8b/2016-03-18_1213.png)

btw, when both feature and story keys are used I can see 4x number of tests in Total

![one_more](http://content.screencast.com/users/dmitrykonovalov/folders/Jing/media/a1f35e4b-472f-4831-b1b0-50d7a9ef9772/2016-03-18_1215.png)

**Comment by smecsia** [comment]
@d-konovalov Are you sure, that you're using the right version of allure report builder? You've provided the screenshot without top bar, where version is present.

**Comment by d-konovalov** [comment]
@smecsia 
here is bigger one

![another](http://content.screencast.com/users/dmitrykonovalov/folders/Jing/media/1509b5c3-25ce-4ec2-9bfe-edcea58883f5/2016-03-18_1244.png)

**Comment by smecsia** [comment]
@d-konovalov thanks. We'll take an additional look then.

**Comment by baev** [comment]
Sorry guys, my bad. Already fixed, will release ASAP

**Comment by dw512** [comment]
@smecsia  Hi,i have already update  report build tool to version 1.4.22, you can see it from the report top bar,but this can't resolve this problem.
@baev ,i want to know the reason,can you show it to us? and we all want to know when the new version can be release to resolve the problem. thanks a lot.
![image](https://cloud.githubusercontent.com/assets/12636008/13910247/fd1741f6-ef59-11e5-826b-3ed9ca670add.png)

**Comment by smecsia** [comment]
@dw512 @d-konovalov [1.4.23 release](https://github.com/allure-framework/allure-core/releases/tag/allure-core-1.4.23) of allure builder has been already shipped. Please verify the problem is solved.

**Comment by dw512** [comment]
@smecsia I am downloading the version 1.4.23 now,then i will check this problem.
may i ask you a question? i see the allure-rspec example in your project, i want to know how many parameters can be attached in "describe" and " it" ,just like the following example:
![image](https://cloud.githubusercontent.com/assets/12636008/13913407/5a468e1e-ef81-11e5-99b8-47e84ec71c76.png)

**Comment by dw512** [comment]
@smecsia I am downloading the version 1.4.23 now,then i will check this problem.
may i ask you a question? i see the allure-rspec example in your project, i want to know how many parameters can be attached in describe and it ,just like the following example:

**Comment by dw512** [comment]
@sharmarahul @smecsia @d-konovalov @baev  @9ikhan  I have already verify the version 1.4.23,it works well,the problem has already fixed. Thanks a lot, @baev  and @smecsia ，good job，thanks for your efforts！
![image](https://cloud.githubusercontent.com/assets/12636008/13914264/2cf71a44-ef88-11e5-88b5-a16f90ddce30.png)

**Comment by d-konovalov** [comment]
@smecsia @baev 
Confirm from my side
thank you guys

**Comment by smecsia** [comment]
@dw512 
>  i want to know how many parameters can be attached in "describe" and " it" 

You can find all allowed metadata labels [here](https://github.com/allure-framework/allure-rspec/blob/master/lib/allure-rspec/formatter.rb#L11). Actually this list is just a copy of [the list built-in into allure model](https://github.com/allure-framework/allure-core/blob/master/allure-model/src/main/resources/allure.xsd#L154).

**Comment by dw512** [comment]
@smecsia thanks a lot, i got it.
