### ISSUE TITLE
Error when using rake task

### ISSUE THREAD

**Issue by timting** [allure-framework/allure-rspec#59]
I tried putting the `config.include AllureRSpec::Adaptor` in both spec_helper.rb and rails_helper.rb. When I try to run `rspec spec\models`, it runs successfully, outputting xml data. When I try to use one of the rake tasks, i.e. `rake spec:models`, it fails with the following error:

```
NameError: uninitialized constant RSpec::Support
/Users/timothy/.rvm/gems/ruby-2.1.0@skillet/gems/rspec-core-3.3.2/lib/rspec/core/formatters/base_formatter.rb:1:in `<top (required)>'
/Users/timothy/.rvm/gems/ruby-2.1.0@skillet/gems/allure-rspec-0.7.4/lib/allure-rspec/formatter.rb:1:in `<top (required)>'
/Users/timothy/.rvm/gems/ruby-2.1.0@skillet/gems/allure-rspec-0.7.4/lib/allure-rspec.rb:3:in `<top (required)>'
```

Looking into this, it seems to be trying to load a specific formatter before RSpec::Core has been loaded.

I'm running RSpec 3.3.0 and Rails 4.1.13. What am I doing wrong? Let me know if you need any more information.

**Comment by smecsia** [comment]
@timting it seems like we should try one of the options described here: [#rspec-rails/issues/1113](https://github.com/rspec/rspec-rails/issues/1113). Can you try to add the `require "rspec/core"` within the allure-rspec formatter and verify if it helps?

**Comment by timting** [comment]
@smecsia I tried that and it seems to work - I added the require statement on line 1 of lib/allure-rspec/formatter.rb

Should I file a PR, or will you take care of it?

**Comment by timting** [comment]
@smecsia thanks for your help - much appreciated.
