### ISSUE TITLE
"Clearing out unresolved specs" causes problems

### ISSUE THREAD

**Issue by d-konovalov** [allure-framework/allure-rspec#65]
Hi guys,
Let's look at screenshot of Jenkins Job console output

![image](http://content.screencast.com/users/dmitrykonovalov/folders/Jing/media/b131c257-cdd0-4a04-bb87-4fbb6d287f95/2016-02-04_1148.png)

Here we can see Passed test suite (0 failures) and also some process started after tests finished
actually this is executing of some code from shared_for_all.rb file where I store a lot of shared_examples (and shared_context) code blocks
It shouldn't run at all here but as you can see it's running

Plus all this stuff ends with this lines:

![image](http://content.screencast.com/users/dmitrykonovalov/folders/Jing/media/b09c7ff2-14c3-4cf3-99cd-c8435a74a4ed/2016-02-04_1145_001.png)

Here we can see some failed runs (I don't know why it's been executed here) 

And line "Build step 'Invoke Rake' marked build as failure" marks current build as failed even when no failures appeared

Please help me here
Also if I should move this issue to the allure-plugin repository just ask, I'll do

Thank you

**Comment by smecsia** [comment]
@d-konovalov It seems that you have job configuration which executes some additional rspec runs... It's hard to say anything without your Jenkins job configuration.

**Comment by d-konovalov** [comment]
Hi @smecsia 
this is rake task which is marked as failed
http://content.screencast.com/users/dmitrykonovalov/folders/Jing/media/9c0e11ae-a556-431b-b008-735cd9be22e9/2016-02-04_1308.png

and this task include three inside:

1. Create test run (in external test management system, I call there only this system methods)
2. Run tests, this code does it:

```ruby
  smoke_spec_path = 'spec/flow_tests/smoke_spec.rb'
  test_params = "--format documentation  --require #{dev_file}"

  RSpec::Core::RakeTask.new(:run_smoke) do |task|
    task.pattern = smoke_spec_path
    task.rspec_opts = test_params + " --format RspecJunitFormatter --out reports/full_smoke.xml --format html --out reports/#{task.name}_report.html"
  end
```

3. Close test run (created in step 1, I call only test system methods here as well, nothing related to tests)


When I made dev:full_smoke task look like this

```ruby

  RSpec::Core::RakeTask.new(:full_smoke) do |task|
    Rake::Task['create_run'].invoke('smoke', namespace.scope.head)
    ENV['run_id'] = test_run_id.to_s
    begin
      Rake::Task["#{namespace.scope.head}:run_smoke"].invoke
    rescue Exception => e
      puts "Task #{task.name} failed"
      puts "#{e.class}: #{e.message}"
      puts "Finished running all tests"
    end
    puts 'before close run'
    Rake::Task['close_run'].invoke(namespace.scope.head)
    puts 'after close run'
  end
```

I've got next result

![image](http://content.screencast.com/users/dmitrykonovalov/folders/Jing/media/767566e5-c067-4aab-9524-e29de099f800/2016-02-04_2257.png)

And the last command according to the provided --pattern is started to run all spec files available in the spec folder

**Comment by d-konovalov** [comment]
That's strange but it was 
```ruby
rescue Exception = e
```
line
when I removed it rake stopped to run twice

**Comment by d-konovalov** [comment]
But this is the case only for failed jobs 
If the job is passed i'm still experiencing double test run

**Comment by smecsia** [comment]
Hmm. I really doubt this particular problem is related to allure-rspec directly. What if you disable allure-rspec from your setup, does it help?

**Comment by d-konovalov** [comment]
This was really not obvious and yes it's not allure related trouble
Thanks
