### ISSUE TITLE
Your report seems to be broken! Check out our FAQ to find a reason Message: {{error.message || error.status}}

### ISSUE THREAD

**Issue by mpahuja** [allure-framework/allure-rspec#66]
I am trying to debug this issue, where the report always has only this shown, I see the xml files though are correctly formatted and screenshots are also named correctly. Attached is a sample of the xml and generated report samples. 
I was using an older version of the allure-rspec (0.7.1) with corresponding rspec (3.2). It was working perfectly fine but something recently started to cause it to fail. Upgrading to latest did not resolve the issue either. Does not seem to be related to allure-rspec but most like allure-cli which now is part of allure-core but did not find any ruby related information on that repo. Hence posting here, any pointers on this would be great.

[log.zip](https://github.com/allure-framework/allure-rspec/files/129447/log.zip)

**Comment by vania-pooh** [comment]
@mpahuja : http://stackoverflow.com/questions/23997449/allure-report-nothing-shown-in-chrome/24002146#24002146

**Comment by mpahuja** [comment]
@vania-pooh My error is different than the one discussed at this and report does open fine for me in all browsers the same. Is it recommending that i run the tests with that flag on?

![image](https://cloud.githubusercontent.com/assets/2895577/13033040/1dd7c532-d2bd-11e5-9993-2e3bab46ee36.png)

**Comment by vania-pooh** [comment]
@mpahuja see https://github.com/allure-framework/allure-core/issues/715 That's a Jenkins CSP restriction.

**Comment by mpahuja** [comment]
Havent changed anything on jenkins side and also i see the same issue locally as well meaning when I run the tests locally and generate the report. So dont think its a CSP issue on jenkins side but will try that as well.

**Comment by mpahuja** [comment]
Still seeing the issue even after making changes on Jenkins, Any ideas why this may be happening?

**Comment by vania-pooh** [comment]
Summon @just-boris.

**Comment by just-boris** [comment]
Have no idea.
@mpahuja what do you see in the browser console?

**Comment by mpahuja** [comment]
Here is what I see in the browser console

@just-boris 
![allureerror](https://cloud.githubusercontent.com/assets/2895577/13440337/704d3d10-dfa6-11e5-8842-930af8ab4774.png)

**Comment by vania-pooh** [comment]
@mpahuja  that's a CSP issue as I said! "Allow-scripts" permission is not set.

**Comment by mpahuja** [comment]
yeah sorry about the confusion, apparently saferestart of jenkins does not pick up the new configuration, had to do a hard restart and now it seems to be working. Thanks for helping here and sorry about the incovienence. BTW Allure reporting has been extremely useful for our team
