### ISSUE TITLE
Duplicate failed tests are reported

### ISSUE THREAD

**Issue by sharmarahul** [allure-framework/allure-rspec#69]
I have just upgraded to the latest allure report generator. My allure report version is now 1.4.20. After the upgrade, I see that twice the number of failed tests are being reported.

**Comment by baev** [comment]
Please use v1.4.23. See https://github.com/allure-framework/allure-core/releases/tag/allure-core-1.4.23

**Comment by sharmarahul** [comment]
@baev Do I have to update it manually? I get latest version already installed when I do this:

`sudo apt-get install allure-commandline
Reading package lists... Done
Building dependency tree       
Reading state information... Done
allure-commandline is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 188 not upgraded.`

**Comment by baev** [comment]
seems like we are forgot to deploy it to apt, I'll deploy it ASAP

**Comment by sharmarahul** [comment]
Brilliant. Thanks

**Comment by sharmarahul** [comment]
@baev I just checked on my system and strange things are being reported for allure. For example: 
`sudo apt-get install --only-upgrade allure-commandline
Reading package lists... Done
Building dependency tree       
Reading state information... Done
allure-commandline is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 188 not upgraded.`
displays that I have the latest already!

When I do 

`dpkg -s allure-commandline
Package: allure-commandline
Status: install ok installed
Priority: extra
Section: misc
Installed-Size: 15343
Maintainer: Ivan Krutov <vania-pooh@yandex-team.ru>
Architecture: all
Version: 1.4.23-1` 

shows the same.
however, when I do allure -version I get 1.4.20

Also on the actual report in the header it says 1.4.20.

**Comment by baev** [comment]
@sharmarahul yep, it was a bug. BTW all should be fine for now (wait a bit while it is been deployed)

**Comment by baev** [comment]
thanks for the report!

**Comment by baev** [comment]
@sharmarahul you can try it out

**Comment by sharmarahul** [comment]
@baev works now! Thanks.
