### ISSUE TITLE
How to add desciption in report

### ISSUE THREAD

**Issue by elangovan-selvaraj** [allure-framework/allure-rspec#73]
We have it name  as test_case. I want to add description for the "it" block. 

http://ci.qatools.ru/job/allure-core_master-deploy/lastSuccessfulBuild/Allure_report/

**Comment by smecsia** [comment]
@elangovan91 It would be better if you could provide the example code, you're using.

**Comment by elangovan91** [comment]
it "testcase title is here" do |e|
     e.step "Step 1" do
     end
end

I want like this
![desctop screenshot](https://cloud.githubusercontent.com/assets/7815693/16688481/e2535502-453b-11e6-93df-5b78ba8c4989.png)

This is my output image
![screen shot 2016-07-08 at 6 44 49 pm](https://cloud.githubusercontent.com/assets/7815693/16688559/34d3d892-453c-11e6-93dd-3a16640895de.png)

**Comment by elangovan91** [comment]
In junit have the annotations for description ( @description ), But in ruby it doesn't have.
