### ISSUE TITLE
Using alternative to testId tag

### ISSUE THREAD

**Issue by MiluchOK** [allure-framework/allure-rspec#79]
Hi, I am in process of implementing allure in a rspec framework and I faced a problem. I already have every test tagged by a `crail_id` tag and this value is being used down the pipe in multiple places, so changing the tag name is not that easy for me. 

I had a feeling that I could just add the `testId` to metadata, but it is not being picked up by the allure reports.

Could you shed some light on this?

**Comment by smecsia** [comment]
@MiluchOK Can you please indicate which version of Allure builder you're using. allure-rspec is currently building xmls in the old Allure format (which is supported by the new version though). 
I tried to reproduce your case with Allure 2.3.5, and I could not. As you can see [here](https://github.com/allure-framework/allure-rspec/blob/master/spec/another_spec.rb#L14) it is passing `:testId` as an additional metadata and I tested it on my local - it works. Report is showing a reference to test with id 10.

**Comment by MiluchOK** [comment]
@smecsia I failed to explain the problem. The problem I am facing is that I have another name for ID tags (not `:testId`) in my framework and renaming the tag is not an option due to tech. reasons. Is it possible to keep using another tag as ID, but make it possible for allure to pick it up?

**Comment by smecsia** [comment]
Unfortunately it is not possible at the moment. There is a list of allowed metadata tags.
