### ISSUE TITLE
when will this support multi describe case?

### ISSUE THREAD

**Issue by WoolenWang** [allure-framework/allure-rspec#83]
i have some case like:
```ruby
describe 'A' do
    describe 'AA' do
         it 'A should be able do AA' do
              "AA".should be_equal("AA")
         end
         describe 'AAA' do
             it 'A should be able do AA' do
                  "AAA".should be_equal("AAA")
             end
         end
    end
end
```
some case like that is a multi level tree like case

when i use this allure-rspec , this kind of case is not support to generate the report.
when did we schedule to support this?

**Comment by AlanFoster** [comment]
I'm running into this issue too; On a code base with ~20,000 tests reported via junit, there's only 16,000 being recorded by allure.
